from .animal import Animal
from .anaconda import Anaconda
from .mamba import Mamba
from .boa import Boa
from .blind import Blind
from .queen import Queen
from .turtle import Turtle
from .frog import Frog
from .goldfish import Goldfish
from .mallard import Mallard
from .waterbug import Water_Bug
from .cow import Cow
from .llama import Llama
from .donkey import Donkey
from .horse import Horse
from .goat import Goat
from .goose import Goose
